version: '2'
services:
  activiti-cloud-audit:
    image: activiti/activiti-cloud-audit:latest
    external_links:
      - activiti-cloud-sso-idm
      - rabbitmq
      - activiti-cloud-registry
    environment:
      - ACT_AUDIT_PORT=8181
    networks:
      - infrastructure
    # activiti-cloud-audit:
        # image: activiti/activiti-cloud-audit-mongodb:7-201710-EA
        # external_links:
          # - activiti-cloud-sso-idm:activiti-cloud-sso-idm
          # - rabbitmq:rabbitmq
          # - activiti-cloud-registry:activiti-cloud-registry
        # depends_on:
          # - mongo
        # environment:
          # - ACT_AUDIT_PORT=8181
          # - ACT_AUDIT_MONGO_HOST=mongo
          # - ACT_AUDIT_MONGO_PORT=27017
          # - ACT_AUDIT_MONGO_DB=activitidb
    # mongo:
        # image: mongo
        # ports:
         # - "27017:27017"
  activiti-cloud-query:
    image: activiti/activiti-cloud-query:latest
    external_links:
      - activiti-cloud-sso-idm
      - rabbitmq
      - activiti-cloud-registry
    environment:
      - ACT_QUERY_PORT=8182
    networks:
      - infrastructure
  # We define the name and the base image of our Runtime Bundle
  rb-my-app:
      # Set image: to whichever you are using
      # This image was generated by the docker-runtime-bundle/Dockerfile
      image: rb-my-app:latest
      ports:
       - "8081:8081"
      # This image was generated by the maven-runtime-bundle project
      #image: rb-my-maven-app
      external_links:
        - activiti-cloud-sso-idm
        - activiti-cloud-registry
        - rabbitmq
      depends_on:
        - rb-postgres
      # You can launch as many Runtime Bundles as you want by changing these Env variables
      environment:
        - ACT_RB_PORT=8081
        - ACT_RB_HOST=rb-my-app
        - ACT_RB_APP_NAME=rb-my-app
        - ACT_RB_DB_URI=jdbc:postgresql://rb-postgres:5432/activitidb
        - ACT_RB_DB_USER=postgres
        - ACT_RB_DB_PASS=password
        - ACT_RB_DB_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
      networks:
        - infrastructure
  # We decided to configure our runtime bundle against a PostgreSQL instance
  rb-postgres:
      image: postgres
      ports:
       - "5432:5432"
      environment:
        - POSTGRES_PASSWORD=password
        - POSTGRES_USER=postgres
        - POSTGRES_DB=activitidb
      networks:
        - infrastructure
# we will join the infrastructure network defined by the infrastructure docker compose.
networks:
  infrastructure:
    external:
      name: docker_default
